 # -*- Tcl -*-
# $Id: cz.msg 494 2011-07-01 21:48:58Z tlu $
# A
::msgcat::mcset cz "Add" "Add"
::msgcat::mcset cz "Add key" "Add key"
::msgcat::mcset cz "Add customer" "Add customer"
::msgcat::mcset cz "Add hardlock" "Add hardlock"
::msgcat::mcset cz "Add product" "Add product"
::msgcat::mcset cz "Add license" "Add license"
::msgcat::mcset cz "Address" "Address"
::msgcat::mcset cz "Are you sure to remove this key from current customer?" "Are you sure to remove this key from current customer?"
::msgcat::mcset cz "Are you sure to remove this license from current key?" "Are you sure to remove this license from current key?"
::msgcat::mcset cz "Are you sure you want to quit?" \
"Are you sure you want to quit?"
# C
::msgcat::mcset cz "Customers" "Customers"
::msgcat::mcset cz "Customer" "Customer"
::msgcat::mcset cz "CustomerId" "CustomerId"
::msgcat::mcset cz "Customer list" "Customer list"
::msgcat::mcset cz "City" "City"
::msgcat::mcset cz "Close" "Close"
::msgcat::mcset cz "Comment" "Comment"
::msgcat::mcset cz "Customer Sheet" "Customer Sheet"
# D
::msgcat::mcset cz "Date in" "Date in"
::msgcat::mcset cz "Date out" "Date out"
::msgcat::mcset cz "Doc No" "Doc No"
::msgcat::mcset cz "Done" "Done"
# E
::msgcat::mcset cz "en" "cz"
::msgcat::mcset cz "Error during conection to database %s" "Error during conection to database %s"
::msgcat::mcset cz "End before days:" "End before days:"
::msgcat::mcset cz "Error" "Error"
# F
::msgcat::mcset cz "First release" "First release"
::msgcat::mcset cz "Filters" "Filters"
::msgcat::mcset cz "Filters of licenses" "Filters of licenses"
::msgcat::mcset cz "Filters of maintenanse" "Filters of maintenanse"
::msgcat::mcset cz "Find" "Find"
# G
::msgcat::mcset cz "Go" "Idte"
::msgcat::mcset cz "Generate PDF" "Generate PDF"
# H
::msgcat::mcset cz "Hardlocks and Felics" "Hardlocks and Felics"
::msgcat::mcset cz "Hardlock" "Hardlock"
# I
::msgcat::mcset cz "Import license" "Import license"
::msgcat::mcset cz "Import licenses from file" "Import licenses from file"
# K
::msgcat::mcset cz "Kind" "Kind"
# L
::msgcat::mcset cz "Licenses Protections Management System, rev. %s"\
   "Licenses Protections Management System, rev. %s" 
::msgcat::mcset cz "List of dongles and flying licenses" "List of dongles and flying licenses"
::msgcat::mcset cz "List of customers" "List of customers"
::msgcat::mcset cz "List of products" "List of products"
::msgcat::mcset cz "List of releases" "List of releases"
::msgcat::mcset cz "License No" "License No"
::msgcat::mcset cz "Last release" "Last release"
::msgcat::mcset cz "License sheet" "License sheet"
::msgcat::mcset cz "List Export" "List Export"
# M
::msgcat::mcset cz "main/additional" "main/additional"
::msgcat::mcset cz "Modify" "Modify"
::msgcat::mcset cz "Modify key" "Modify key"
::msgcat::mcset cz "Modify customer" "Modify customer"
::msgcat::mcset cz "Modify product" "Modify product" 
::msgcat::mcset cz "Modify license" "Modify license"
::msgcat::mcset cz "Maintenance" "Maintenance"
::msgcat::mcset cz "Maintenance Date" "Maintenance Date"
# N
::msgcat::mcset cz "Number" "Number"
::msgcat::mcset cz "Name" "Name"
::msgcat::mcset cz "Number/HostId" "Number/HostId"
# O
::msgcat::mcset cz "Oops" "Oops" 
::msgcat::mcset cz "Open" "Open"
# P
::msgcat::mcset cz "Products and Releases" "Products and Releases"
::msgcat::mcset cz "Product" "Product"
::msgcat::mcset cz "Product exists" "Product exists"
::msgcat::mcset cz "ProductId" "ProductId"
::msgcat::mcset cz "Please wait..." "Please wait..."
::msgcat::mcset cz "Person" "Person"
::msgcat::mcset cz "Phone" "Phome"
# Q
::msgcat::mcset cz "Quantity" "Quantity"
# R
::msgcat::mcset cz "Replace key" "Replace key"
::msgcat::mcset cz "Replace" "Replace" 
::msgcat::mcset cz "Refresh" "Refresh" 
::msgcat::mcset cz "Remove" "Remove"
::msgcat::mcset cz "Remove key" "Remove key"
# S
::msgcat::mcset cz "Stats" "Stats"
::msgcat::mcset cz "Status" "Status"
::msgcat::mcset cz "Save" "Save"
::msgcat::mcset cz "Save to file" "Save to file"
# V
::msgcat::mcset cz "Valid until" "Valid until" 
::msgcat::mcset cz "View PDF" "View PDF"
# Z
::msgcat::mcset cz "Zip code" "Zip code"
# EOF
