 # -*- Tcl -*-
# $Id: en.msg 355 2009-04-05 12:23:12Z tlu $
# A
::msgcat::mcset en "Add" "Add"
::msgcat::mcset en "Add key" "Add key"
::msgcat::mcset en "Add customer" "Add customer"
::msgcat::mcset en "Add hardlock" "Add hardlock"
::msgcat::mcset en "Add product" "Add product"
::msgcat::mcset en "Add license" "Add license"
::msgcat::mcset en "Address" "Address"
::msgcat::mcset en "Are you sure to remove this key from current customer?" "Are you sure to remove this key from current customer?"
::msgcat::mcset en "Are you sure to remove this license from current key?" "Are you sure to remove this license from current key?"
::msgcat::mcset en "Are you sure you want to quit?" \
"Are you sure you want to quit?"
# C
::msgcat::mcset en "Customers" "Customers"
::msgcat::mcset en "Customer" "Customer"
::msgcat::mcset en "CustomerId" "CustomerId"
::msgcat::mcset en "Customer list" "Customer list"
::msgcat::mcset en "City" "City"
::msgcat::mcset en "Close" "Close"
::msgcat::mcset en "Comment" "Comment"
::msgcat::mcset en "Customer Sheet" "Customer Sheet"
# D
::msgcat::mcset en "Date in" "Date in"
::msgcat::mcset en "Date out" "Date out"
::msgcat::mcset en "Date sold" "Date sold"
::msgcat::mcset en "Doc No" "Doc No"
::msgcat::mcset en "Done" "Done"
# E
::msgcat::mcset en "en" "en"
::msgcat::mcset en "Error during conection to database %s" "Error during conection to database %s"
::msgcat::mcset en "End before days:" "End before days:"
::msgcat::mcset en "Error" "Error"
::msgcat::mcset en "Expired" "Exired"
::msgcat::mcset en "Export v2c file" "Export v2c file"
# F
::msgcat::mcset en "First release" "First release"
::msgcat::mcset en "Filters" "Filters"
::msgcat::mcset en "Filters of licenses" "Filters of licenses"
::msgcat::mcset en "Filters of maintenanse" "Filters of maintenanse"
::msgcat::mcset en "Find" "Find"
# G
::msgcat::mcset en "Go" "Go"
::msgcat::mcset en "Generate PDF" "Generate PDF"
# H
::msgcat::mcset en "Hardlocks and Felics" "Hardlocks and Felics"
::msgcat::mcset en "Hardlock" "Hardlock"
# I
::msgcat::mcset en "Import v2c file" "Import v2c file"
::msgcat::mcset en "Import license" "Import license"
::msgcat::mcset en "Import licenses from file" "Import licenses from file"
# K
::msgcat::mcset en "Keys" "Keys"
::msgcat::mcset en "Kind" "Kind"
# L
::msgcat::mcset en "Licenses Protections Management System, rev. %s"\
   "Licenses Protections Management System, rev. %s" 
::msgcat::mcset en "List of dongles and flying licenses" "List of dongles and flying licenses"
::msgcat::mcset en "List of customers" "List of customers"
::msgcat::mcset en "List of products" "List of products"
::msgcat::mcset en "List of releases" "List of releases"
::msgcat::mcset en "License No" "License No"
::msgcat::mcset en "Last release" "Last release"
::msgcat::mcset en "License sheet" "License sheet"
::msgcat::mcset en "Licenses status" "Licenses status"
::msgcat::mcset en "List Export" "List Export"
# M
::msgcat::mcset en "main/additional" "main/additional"
::msgcat::mcset en "Modify" "Modify"
::msgcat::mcset en "Modify key" "Modify key"
::msgcat::mcset en "Modify customer" "Modify customer"
::msgcat::mcset en "Modify product" "Modify product" 
::msgcat::mcset en "Modify license" "Modify license"
::msgcat::mcset en "Maintenance" "Maintenance"
::msgcat::mcset en "Maintenance Date" "Maintenance Date"
# N
::msgcat::mcset en "Number" "Number"
::msgcat::mcset en "Name" "Name"
::msgcat::mcset en "Number/HostId" "Number/HostId"
# O
::msgcat::mcset en "Oops" "Oops" 
::msgcat::mcset en "Open" "Open"
# P
::msgcat::mcset en "Products and Releases" "Products and Releases"
::msgcat::mcset en "Product" "Product"
::msgcat::mcset en "Product exists" "Product exists"
::msgcat::mcset en "ProductId" "ProductId"
::msgcat::mcset en "Please wait..." "Please wait..."
::msgcat::mcset en "Person" "Person"
::msgcat::mcset en "Phone" "Phome"
# Q
::msgcat::mcset en "Quantity" "Quantity"
# R
::msgcat::mcset en "Replace key" "Replace key"
::msgcat::mcset en "Replace" "Replace" 
::msgcat::mcset en "Refresh" "Refresh" 
::msgcat::mcset en "Remove" "Remove"
::msgcat::mcset en "Remove key" "Remove key"
# S
::msgcat::mcset en "Stats" "Stats"
::msgcat::mcset en "Status" "Status"
::msgcat::mcset en "Save" "Save"
::msgcat::mcset en "Save to file" "Save to file"
# T
::msgcat::mcset en "Terminal" "Terminal"
# V
::msgcat::mcset en "Valid until" "Valid until" 
::msgcat::mcset en "View PDF" "View PDF"
# Z
::msgcat::mcset en "Zip code" "Zip code"
# EOF
