# -*- Tcl -*-
# $Id: pl.msg 355 2009-04-05 12:23:12Z tlu $
# A
::msgcat::mcset pl "Add" "Dodaj"
::msgcat::mcset pl "Add key" "Dodaj klucz"
::msgcat::mcset pl "Add customer" "Dodaj klienta"
::msgcat::mcset pl "Add hardlock" "Dodaj klucz"
::msgcat::mcset pl "Add product" "Dodaj produkt"
::msgcat::mcset pl "Add license" "Dodaj licencję"
::msgcat::mcset pl "Address" "Adres"
::msgcat::mcset pl "Are you sure to remove this key from current customer?" "Na pewno usunąć klucz z bieżącego klienta?"
::msgcat::mcset pl "Are you sure to remove this license from current key?" "Na pewno usunąć licencję z bieżącego klucza?"
::msgcat::mcset pl "Are you sure you want to quit?" \
"Czy na pewno zamknąć program?"
# C
::msgcat::mcset pl "Customers" "Klienci"
::msgcat::mcset pl "Customer" "Klient"
::msgcat::mcset pl "CustomerId" "Nr klienta"
::msgcat::mcset pl "Customer list" "Lista klientów"
::msgcat::mcset pl "City" "Miasto"
::msgcat::mcset pl "Close" "Zamknij"
::msgcat::mcset pl "Comment" "Komentarz"
::msgcat::mcset pl "Customer Sheet" "Arkusz klienta"
# D
::msgcat::mcset pl "Date in" "Data przyjęcia"
::msgcat::mcset pl "Date out" "Data wydania"
::msgcat::mcset pl "Date sold" "Data sprzedaży"
::msgcat::mcset pl "Doc No" "Nr dokumentu"
::msgcat::mcset pl "Done" "Gotowe"
# E
::msgcat::mcset pl "en" "pl"
::msgcat::mcset pl "Error during conection to database %s" "Błąd podczas łączenia z bazą %s"
::msgcat::mcset pl "End before days:" "Upływa w ciągu dni:"
::msgcat::mcset pl "Error" "Błąd"
::msgcat::mcset pl "Expired" "Wygasłe"
::msgcat::mcset pl "Export v2c file" "Eksport pliku v2c"
# F
::msgcat::mcset pl "First release" "Pierwsza wersja"
::msgcat::mcset pl "Filters" "Filtry"
::msgcat::mcset pl "Filters of licenses" "Filtr licencji"
::msgcat::mcset pl "Filters of maintenanse" "Filtr opieki technicznej"
::msgcat::mcset pl "Find" "Szukaj"
# G
::msgcat::mcset pl "Go" "Idź do"
::msgcat::mcset pl "Generate PDF" "Generuj PDF"
# H
::msgcat::mcset pl "Hardlocks and Felics" "Klucze i licencje pływające"
::msgcat::mcset pl "Hardlock" "Klucz"
# I
::msgcat::mcset pl "Import v2c file" "Import pliku v2c"
::msgcat::mcset pl "Import license" "Import licencji"
::msgcat::mcset pl "Import licenses from file" "Import licencji z pliku"
# K
::msgcat::mcset pl "Keys" "Klucze"
::msgcat::mcset pl "Kind" "Rodzaj"
# L
::msgcat::mcset pl "Licenses Protections Management System, rev. %s"\
    "Menadżer kluczy i licencji, wersja %s"
::msgcat::mcset pl "List of dongles and flying licenses" "Lista kluczy i licencji pływających"
::msgcat::mcset pl "List of customers" "Lista klientów"
::msgcat::mcset pl "List of products" "Lista produktów"
::msgcat::mcset pl "List of releases" "Lista wersji"
::msgcat::mcset pl "License No" "Numer licencji"
::msgcat::mcset pl "Last release" "Ostatnia wersja"
::msgcat::mcset pl "License sheet" "Arkusz licencji"
::msgcat::mcset pl "Licenses status" "Status licencji"
::msgcat::mcset pl "List Export" "Eksport listy"
# M
::msgcat::mcset pl "main/additional" "podstawowa/dodatkowa"
::msgcat::mcset pl "Modify" "Zmień"
::msgcat::mcset pl "Modify key" "Zmień klucz"
::msgcat::mcset pl "Modify customer" "Zmień klienta"
::msgcat::mcset pl "Modify product" "Zmień produkt"
::msgcat::mcset pl "Modify license" "Zmień licencję"
::msgcat::mcset pl "Maintenance" "Opieka"
::msgcat::mcset pl "Maintenance Date" "Data opieki"
# N
::msgcat::mcset pl "Number" "Numer"
::msgcat::mcset pl "Name" "Nazwa"
::msgcat::mcset pl "Number/HostId" "Numer/HostId"
# O
::msgcat::mcset pl "Oops" "OOps"
::msgcat::mcset pl "Open" "Otwórz"
# P
::msgcat::mcset pl "Products and Releases" "Produkty i wersje"
::msgcat::mcset pl "Product" "Produkt"
::msgcat::mcset pl "Product exists" "Produkt już istnieje"
::msgcat::mcset pl "ProductId" "Nr produktu"
::msgcat::mcset pl "Please wait..." "Proszę czekać..."
::msgcat::mcset pl "Person" "Osoba"
::msgcat::mcset pl "Phone" "Telefon"
# Q
::msgcat::mcset pl "Quantity" "Liczba"
# R
::msgcat::mcset pl "Replace key" "Zamiana klucza"
::msgcat::mcset pl "Replace" "Zastąp"
::msgcat::mcset pl "Refresh" "Odśwież"
::msgcat::mcset pl "Remove" "Usuń"
::msgcat::mcset pl "Remove key" "Usuń klucz"
# S
::msgcat::mcset pl "Stats" "Statystyka"
::msgcat::mcset pl "Status" "Status"
::msgcat::mcset pl "Save" "Zapisz"
::msgcat::mcset pl "Save to file" "Zapisz do pliku"
# T
::msgcat::mcset pl "Terminal" "Czasowe"
# V
::msgcat::mcset pl "Valid until" "Ważne do"
::msgcat::mcset pl "View PDF" "Podgląd PDF"
# Z
::msgcat::mcset pl "Zip code" "Kod"
# Do sprawdzenia
::msgcat::mcset pl "yes" "Tak"
::msgcat::mcset pl "no" "Nie"

# 2007.03.10 TLu
